Added changes for allowing CPU and Memory limitation
InterDigitalInc/AdvantEDGE pull request #149
Opened 2020-11-05 17:13 UTC by nikhildoifode

Changes:
- Changed meep_model.yaml for generating request and limits for cpu and memory
- Changed backend to support cpu and memory limitations
- Changed frontend for accepting values for cpu and memory min and max values
- Added cypress test to test cpu and memory values

Test:
- All UT's passed
- All cypress tests passed

2020-11-05 20:53 UTC, dilallkx requested changes
You are also missing the following to complete the model update:
- meepctl & repocfg & meep-model validator:
   - Bump version
NOTE: This is required to make sure that scenarios that use the new model fields can only be used with the latest platform version.

2020-11-06 14:46 UTC, nikhildoifode commented on js-apps/meep-frontend/src/js/containers/cfg/cfg-network-element-container.js
> +    return 'count !== 0';
Done

2020-11-06 14:46 UTC, nikhildoifode commented on js-apps/meep-frontend/src/js/containers/cfg/cfg-network-element-container.js
> +    return 'count !== 0 ';
Done

2020-11-06 14:46 UTC, nikhildoifode commented on js-apps/meep-frontend/src/js/containers/cfg/cfg-network-element-container.js
> +        label="Max memory (MB)"
Done

2020-11-06 14:46 UTC, nikhildoifode commented on js-apps/meep-frontend/src/js/containers/cfg/cfg-network-element-container.js
> +        label="Min CPU"
Done

2020-11-06 14:47 UTC, nikhildoifode commented on js-apps/meep-frontend/src/js/containers/cfg/cfg-page-container.js
> +        this.props.cfgElemSetErrMsg('Min CPU > Max CPU which is not acceptable');
Done

2020-11-06 14:47 UTC, nikhildoifode commented on js-apps/meep-frontend/src/js/containers/cfg/cfg-page-container.js
> +        this.props.cfgElemSetErrMsg('Min Memory > Max Memory which is not acceptable');
Done

2020-11-06 14:47 UTC, nikhildoifode commented on js-apps/meep-frontend/src/js/util/scenario-utils.js
> +    process.cpuConfig = {
Done

2020-11-06 15:29 UTC, nikhildoifode commented
Bumped version for Repocfg, Meepctl and meep-model

2020-11-06 15:57 UTC, dilallkx approved these changes

2020-11-06 15:57 UTC, merged