Location API zonalStatus fix
InterDigitalInc/AdvantEDGE pull request #162
Opened 2020-11-30 18:37 UTC by pastorsx

ZonalStatus AP threshold fix (code not hit)
Mandatory info in bodies checked for all location API subscription, if not there, returning BadRequest error.

no impact on UT or cypress.

2020-12-02 16:04 UTC, dilallkx requested changes

2020-12-08 15:17 UTC, pastorsx commented on go-apps/meep-loc-serv/server/loc-serv.go
> +var previousNbUsersInZone int
removed previous variables, used the stored values
removed the function that just added complexity for direct calls

2020-12-08 15:20 UTC, pastorsx commented on go-apps/meep-loc-serv/server/loc-serv.go
> +				}
yes, and i merged the 2 ifs as requested, fixed

2020-12-08 15:20 UTC, pastorsx commented on go-apps/meep-loc-serv/server/loc-serv.go
>  				}
fixed

2020-12-08 15:20 UTC, pastorsx commented on go-apps/meep-loc-serv/server/loc-serv.go
> +	previousNbUsersInZone = 0
fixed

2020-12-08 20:05 UTC, dilallkx approved these changes

2020-12-08 20:05 UTC, merged