D2d GIS Engine API Updates
InterDigitalInc/AdvantEDGE pull request #399
Opened 2022-10-19 18:40 UTC by dhruvigoyal25

Updates:

- Updated meep-model: geoData with d2dInRange and poaInRange Info
- Updated Gis Engine API to populate these info to geoData

2022-10-26 14:24 UTC, dilallkx requested changes

2022-10-26 14:48 UTC, dhruvigoyal25 commented on js-apps/meep-frontend/src/js/containers/idc-map.js
> +  checkD2d(marker) {
Addressed.

2022-10-26 14:48 UTC, dhruvigoyal25 commented on js-apps/meep-frontend/src/js/containers/idc-map.js
> +    var ifpoa = false;
Addressed

2022-10-31 16:47 UTC, dhruvigoyal25 commented on js-apps/meep-frontend/src/js/containers/idc-map.js
> +        marker.options.meep.ue.range.setStyle({color: color});
The range is set only for d2d devices.

2022-10-31 16:47 UTC, dhruvigoyal25 commented on js-apps/meep-frontend/src/js/containers/idc-map.js
> +      }
Addressed with updated logic.

2022-11-01 20:31 UTC, dilallkx approved these changes

2022-11-01 20:31 UTC, merged