Seq Diagram Fixes
InterDigitalInc/AdvantEDGE pull request #404
Opened 2022-11-15 21:44 UTC by dhruvigoyal25

This PR contains the following fixes:
1. State change for a pause of sequence logs
2. Export takes a lot of time.

2022-11-28 23:08 UTC, dilallkx requested changes
Please address the provided comments.
Thanks!

2022-11-29 22:56 UTC, dhruvigoyal25 commented on go-packages/meep-metrics/metric-store.go
> +func (ms *MetricStore) GetTagStr(inputTagStr string, timeStart string, timeStop string, duration string) string {
Addressed.

2022-11-29 22:56 UTC, dhruvigoyal25 commented on go-packages/meep-metrics/metric-store.go
> +	valuesArray := []map[string]interface{}{}
Addressed.

2022-11-29 22:56 UTC, dhruvigoyal25 commented on go-packages/meep-metrics/metric-store.go
> +		if len(response.Results) > 0 && len(response.Results[0].Series) > 0 {
Addressed.

2022-11-30 01:45 UTC, dilallkx approved these changes

2022-11-30 01:46 UTC, merged